name = "p2p-signal"
main = "src/worker.js"
compatibility_date = "2025-09-01"

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "Room" }
]

# IMPORTANT: Make the Durable Object SQLite-backed
[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]
